Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()



# add the general drivers.
src = Split("""
""")

src += ['treaty_base_lsb.c']
src += ['treaty_base_msb.c']

if GetDepend(['BRD_DAC_HT5320']):
    src += ['dac_ht5320.c']

if GetDepend(['BRD_DAC_MCP4728']):
    src += ['dac_mcp4728.c']
    
if GetDepend(['BRD_DFS_NOR_FLASH']):
    src += ['sfud_init_app.c']   

if GetDepend(['BRD_GPS_BD']):
    src += ['gps_bd.c']    

if GetDepend(['BRD_RTC_AIP1307']):
    src += ['RTC_AiP1307SA8.c']    

if GetDepend(['BRD_RTC_PCF8563']):
    src += ['rtc_pcf8563.c']    

if GetDepend(['BRD_RTC_DS1307']):
    src += ['drv_rtc_ds1307.c']   

if GetDepend(['LIB_CRC_XOR']):
    src += ['crc_xor.c']   

path =  [cwd]
path += [cwd + '/config']

group = DefineGroup('user_periph', src, depend = [''], CPPPATH = path)

Return('group')

